#pragma once

#define WIFI_SSID "REPLACE_WITH_WIFI_SSID"
#define WIFI_PASSWORD "REPLACE_WITH_WIFI_PASSWORD"

#define FIREBASE_API_KEY "REPLACE_WITH_FIREBASE_WEB_API_KEY"
#define FIREBASE_PROJECT_ID "bhoomifi"
#define FIREBASE_DEVICE_ID "BHOOMIFI-ESP32-NODE-01"
#define FIREBASE_DEVICE_EMAIL "REPLACE_WITH_DEVICE_AUTH_EMAIL"
#define FIREBASE_DEVICE_PASSWORD "REPLACE_WITH_DEVICE_AUTH_PASSWORD"
#define FIREBASE_DEVICE_UID "REPLACE_WITH_DEVICE_AUTH_UID"
